"""
Django settings for main_app project.

Generated by 'django-admin startproject' using Django 2.1.7.
"""

import os
import environ
env = environ.Env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&%up9@!s_$$duan4(qurnori____2#kg!_+m_-^j$2-vzibx&p'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
try:
    DEBUG = os.environ['DJANGO_DEBUG'].lower() == 'true'
except:
    DEBUG = False
print('Django setting: DEBUG =', DEBUG)


ALLOWED_HOSTS = ['*', 'planner.kandbox.com']

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'django.contrib.admindocs',
    # https://django-axes.readthedocs.io/en/latest/2_installation.html
    'axes',
    ###-------------------------------------------------------###
    'kpdata',
    # 'demo', 
    # 'sales_forecast',
]


AUTHENTICATION_BACKENDS = [
    # AxesBackend should be the first backend in the AUTHENTICATION_BACKENDS list.
    'axes.backends.AxesBackend',

    # Django ModelBackend is the default authentication backend.
    'django.contrib.auth.backends.ModelBackend',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'main_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SESSION_EXPIRE_AT_BROWSER_CLOSE=True
# By default, SESSION_EXPIRE_AT_BROWSER_CLOSE is set to False, which means session cookies will be stored in users’ browsers for as long as SESSION_COOKIE_AGE. Use this if you don’t want people to have to log in every time they open a browser.
# https://docs.djangoproject.com/en/3.0/topics/http/sessions/


# 2020-04-13 07:46:59
# =1 get None. Without any axes setting, get 127.0.0.1 

AXES_PROXY_COUNT=0

IPWARE_META_PRECEDENCE_ORDER = ( 
    'HTTP_X_FORWARDED_FOR',
    'X-Real-IP',
    'X-Forwarded-For',
    'X_REAL_IP',
    'REMOTE_ADDR',
)
AXES_META_PRECEDENCE_ORDER =  IPWARE_META_PRECEDENCE_ORDER 
IPWARE_HTTP_HEADER_PRECEDENCE_ORDER = IPWARE_META_PRECEDENCE_ORDER
'''
'''
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication'
    ],
    'DATETIME_FORMAT': "%Y-%m-%dT%H:%M:%S"
}


WSGI_APPLICATION = 'main_app.wsgi.application'


DATABASES = {"default":  env.db("KPDJANGO_DATABASE_URL")}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

#LANGUAGE_CODE = 'zh-hans'
LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'ja'


TIME_ZONE = 'Europe/London'

USE_I18N = True

USE_L10N = True

USE_TZ = False # Because of import-export 2020-04-15 10:17:51

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# STATIC_ROOT = os.path.join(BASE_DIR, "static")


# print('STATIC_ROOT', STATIC_ROOT)
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static") ,) # '/Users/qiyang/Documents/qduan/git/work_git/kandbox_planner/src/temp/main_app/static'


# print('STATICFILES_DIRS', STATICFILES_DIRS)
# simpleui 设置

# 首页配置
# SIMPLEUI_HOME_PAGE = 'https://www.baidu.com'
# 首页标题
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# 首页图标,支持element-ui的图标和fontawesome的图标
# SIMPLEUI_HOME_ICON = 'el-icon-date'

# 设置simpleui 点击首页图标跳转的地址
SIMPLEUI_INDEX = '/'

# 首页显示服务器、python、django、simpleui相关信息
SIMPLEUI_HOME_INFO = False

# 首页显示快速操作
# SIMPLEUI_HOME_QUICK = False

# 首页显示最近动作
# SIMPLEUI_HOME_ACTION = False


# 自定义SIMPLEUI的Logo
# claro_tipobrafico_branco2
# timeline_icon
# 登录页粒子动画，默认开启，False关闭
#


SIMPLEUI_LOGIN_PARTICLES = False

SIMPLEUI_STATIC_OFFLINE = True

# 让simpleui 不要收集相关信息
SIMPLEUI_ANALYSIS = False




my_menus = [    
        {
            'name': 'Visit',
            'icon': 'far fa-calendar-check', # 'fa fa-file',
            'models': [ 
                {
                'name': 'Current Visits',
                'url': '/kpdata/job/',
                'icon': 'far fa-calendar-check'
                },
                {
                'name': 'Chart & Exceptions',
                'url': '/kpdata/vuegamechart/',
                'icon': 'fas fa-bars' # <i class="fas fa-th-large"></i>
                },
                {
                'name': 'Historical Batches',
                'url': '/kpdata/jobstatus/',
                'icon': 'fas fa-tasks'
                },
                {
                'name': 'Change History',
                'url': '/kpdata/jobchangehistory/',
                'icon': 'fas fa-history' # <i class="fas fa-history"></i>
                },
            ]
        },
        {
            'name': 'Tech',
            'icon': 'fas fa-user-tie',
            'url': '/kpdata/worker/'
        },
        {
            'name': 'Dairy Event',
            'icon': 'fas fa-plane-departure',
            'url': '/kpdata/workerabsence/'
        },{
            'app': 'auth',
            'name': 'User Managements',
            'icon': 'fas fa-user-shield',
            'models': [{
                'name': 'Users',
                'icon': 'fa fa-user',
                'url': 'auth/user/'
            }, {
                'name': 'Groups',
                'icon': 'fa fa-users-cog',
                'url': 'auth/group/'
            },{
                'name': 'API Tokens',
                'icon': 'fas fa-passport',  
                'url': 'authtoken/token/'
            },{
                'name': 'Access Logs',
                'icon': 'fas fa-sign-in-alt',  
                'url': 'axes/accesslog/'
            },{
                'name': 'Access Denied',
                'icon': 'fas fa-exclamation-circle',   
                'url': 'axes/accessattempt/'
            }
            ]
        },  ]
 
# 自定义simpleui 菜单
SIMPLEUI_CONFIG = {
    # 在自定义菜单的基础上保留系统模块
    'system_keep': False,  # True, False
    # 'menu_display': ['Visit','Tech', 'Dairy Event', 'User Managements'],  # 'Kpdata', 'Authentication and Authorization'
    'menus': my_menus #[] # 
} 

SIMPLEUI_LOGO = '/static/fa_th_large.png'

# 是否显示默认图标，默认=True
# SIMPLEUI_DEFAULT_ICON = False

# 图标设置，图标参考：
SIMPLEUI_ICON = {
    '系统管理': 'fab fa-apple',
    '员工管理': 'fas fa-user-tie'
}

# 指定simpleui 是否以脱机模式加载静态资源，为True的时候将默认从本地读取所有资源，即使没有联网一样可以。适合内网项目
# 不填该项或者为False的时候，默认从第三方的cdn获取

SIMPLEUI_STATIC_OFFLINE = False
