# Generated by Django 3.0.5 on 2020-05-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLPlannerParameter',
            fields=[
                ('planner_code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('planner_env_class', models.CharField(max_length=250)),
                ('planner_agent_class', models.CharField(max_length=250)),
                ('allow_overtime', models.BooleanField()),
                ('nbr_of_observed_workers', models.IntegerField()),
                ('nbr_of_days_planning_window', models.IntegerField()),
                ('data_start_day', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'kpdata_rl_planner_parameter',
            },
        ),
    ]
